import { Component } from '@angular/core';
import { ComponentFixture, TestBed } from '@angular/core/testing';
import { By } from '@angular/platform-browser';

import { SdAnchorItem } from './anchor-item.component';

// ---------------------------------------------------------------------------
// Host wrappers — SdAnchorItem requires a real template instance so we wrap it.
// ---------------------------------------------------------------------------

@Component({
  standalone: true,
  imports: [SdAnchorItem],
  // why: native title attribute would conflict with input(); host sets it then
  // confirms the effect strips it once the input takes effect.
  template: `
    <sd-anchor-item [title]="title" [icon]="icon" [key]="key" title="native-tooltip">
      <p class="projected">section body</p>
    </sd-anchor-item>
  `,
})
class HostComponent {
  title = 'Phần 1';
  icon: string | undefined = undefined;
  key: string | undefined = undefined;
}

function getItem(fixture: ComponentFixture<unknown>): SdAnchorItem {
  const de = fixture.debugElement.query(By.directive(SdAnchorItem));
  if (!de) throw new Error('SdAnchorItem not found');
  return de.componentInstance as SdAnchorItem;
}

function getItemEl(fixture: ComponentFixture<unknown>): HTMLElement {
  return fixture.debugElement.query(By.directive(SdAnchorItem)).nativeElement as HTMLElement;
}

describe('SdAnchorItem', () => {
  let fixture: ComponentFixture<HostComponent>;
  let host: HostComponent;
  let item: SdAnchorItem;

  beforeEach(async () => {
    await TestBed.configureTestingModule({ imports: [HostComponent] }).compileComponents();
    fixture = TestBed.createComponent(HostComponent);
    host = fixture.componentInstance;
    fixture.detectChanges();
    item = getItem(fixture);
  });

  describe('creation', () => {
    it('creates the component', () => {
      expect(item).toBeTruthy();
    });

    it('exposes an autogenerated uuid as id', () => {
      expect(typeof item.id).toBe('string');
      expect(item.id.length).toBeGreaterThan(0);
    });

    it('renders an internal <section> wrapping projected content', () => {
      const el = getItemEl(fixture);
      const section = el.querySelector('section');
      expect(section).not.toBeNull();
      expect(section!.textContent).toContain('section body');
    });
  });

  describe('inputs', () => {
    it('reads title() input', () => {
      expect(item.title()).toBe('Phần 1');
    });

    it('updates title() when host changes the bound value', () => {
      host.title = 'Phần 2';
      fixture.detectChanges();
      expect(item.title()).toBe('Phần 2');
    });

    it('icon() defaults to undefined', () => {
      expect(item.icon()).toBeUndefined();
    });

    it('icon() reflects bound value', () => {
      host.icon = 'home';
      fixture.detectChanges();
      expect(item.icon()).toBe('home');
    });

    it('key() defaults to undefined', () => {
      expect(item.key()).toBeUndefined();
    });

    it('key() reflects bound value', () => {
      host.key = 'k1';
      fixture.detectChanges();
      expect(item.key()).toBe('k1');
    });
  });

  describe('title attribute side-effect', () => {
    // why: input.title shadows the DOM `title` attribute; effect must strip it
    // so the browser does not pop a native tooltip duplicating the visual label.
    it('removes the native title attribute on the host once title() is set', () => {
      const el = getItemEl(fixture);
      expect(el.hasAttribute('title')).toBe(false);
    });
  });

  describe('elementRef', () => {
    it('exposes a usable ElementRef pointing at the host element', () => {
      const el = getItemEl(fixture);
      expect(item.elementRef.nativeElement).toBe(el);
    });
  });
});
