import { Injectable } from '@angular/core';
import { SdAutoidElement, SdAutoidElementState } from '../models/autoid-element.model';
import { SdAutoidExportMeta } from '../models/autoid-export-format.model';

@Injectable({ providedIn: 'root' })
export class SdAutoidExportService {
  toJson(elements: SdAutoidElement[]): string {
    return JSON.stringify(elements, null, 2);
  }

  toCsv(elements: SdAutoidElement[]): string {
    const header = 'STT,name,autoid,tag,table-scope,disabled,loading,empty,invalid,opened,count,data-value,text,xpath';
    const rows = elements.map(el =>
      [
        el.stt,
        this.q(el.name),
        this.q(el.autoid),
        this.q(el.tag),
        this.q(el.tableScope ?? ''),
        this.q(el.state.disabled ?? ''),
        this.q(el.state.loading ?? ''),
        this.q(el.state.empty ?? ''),
        this.q(el.state.invalid ?? ''),
        this.q(el.state.opened ?? ''),
        this.q(el.state.count ?? ''),
        this.q(el.state.dataValue ?? ''),
        this.q(el.text),
        this.q(el.xpath),
      ].join(',')
    );
    return [header, ...rows].join('\n') + '\n';
  }

  /** POM TypeScript skeleton — copy ngay vào file Playwright/Cypress. */
  toMarkdownPom(elements: SdAutoidElement[], meta: SdAutoidExportMeta): string {
    const className = this.toPascal(meta.pageTitle || 'AutoGenerated') + 'Page';
    const lines: string[] = [];
    lines.push(`# ${className}`);
    lines.push('');
    lines.push(`- Page: \`${meta.pageUrl}\``);
    lines.push(`- Generated: \`${meta.timestamp}\``);
    lines.push('');
    lines.push('```ts');
    lines.push(`export class ${className} {`);
    for (const el of elements) {
      const propName = this.toCamel(el.autoid);
      const nameHint = el.name ? ` ${el.name} —` : '';
      const stateSummary = this.buildStateSummary(el.state);
      const stateStr = stateSummary ? ` — ${stateSummary}` : '';
      lines.push(`  /** ${el.tag}${nameHint}${stateStr} */`);
      lines.push(`  readonly ${propName} = '${el.xpath}';`);
    }
    lines.push('}');
    lines.push('```');
    lines.push('');
    return lines.join('\n');
  }

  /** Markdown reference table, group FIRST by tableScope (top-level first, then per table), then by tag. */
  toMarkdownTable(elements: SdAutoidElement[], meta: SdAutoidExportMeta): string {
    const lines: string[] = [];
    lines.push('# AutoId Reference');
    lines.push('');
    lines.push(`- Page: \`${meta.pageUrl}\``);
    lines.push(`- Generated: \`${meta.timestamp}\``);
    lines.push('');

    // Partition into top-level and per-table buckets.
    const topLevel = elements.filter(el => !el.tableScope);
    // Collect unique table scopes in insertion order (preserves DOM order).
    const tableScopes: string[] = [];
    for (const el of elements) {
      if (el.tableScope && !tableScopes.includes(el.tableScope)) {
        tableScopes.push(el.tableScope);
      }
    }
    tableScopes.sort();

    const renderTagGroup = (items: SdAutoidElement[]) => {
      const groups = new Map<string, SdAutoidElement[]>();
      for (const el of items) {
        const key = el.tag || '(no-tag)';
        if (!groups.has(key)) groups.set(key, []);
        groups.get(key)!.push(el);
      }
      const sortedTags = [...groups.keys()].sort();
      for (const tag of sortedTags) {
        lines.push(`### ${tag}`);
        lines.push('');
        lines.push('| name | autoid | xpath | state | duplicate |');
        lines.push('|------|--------|-------|-------|-----------|');
        for (const el of groups.get(tag)!) {
          const stateSummary = this.buildStateSummary(el.state);
          lines.push(`| ${this.mdCell(el.name)} | \`${el.autoid}\` | \`${el.xpath}\` | ${this.mdCell(stateSummary)} | ${el.duplicate ? '⚠️' : ''} |`);
        }
        lines.push('');
      }
    };

    // Top-level section.
    lines.push('## Top-level');
    lines.push('');
    if (topLevel.length > 0) {
      renderTagGroup(topLevel);
    } else {
      lines.push('_(no top-level elements)_');
      lines.push('');
    }

    // Per-table sections.
    for (const scope of tableScopes) {
      lines.push(`## Inside table \`${scope}\``);
      lines.push('');
      const scopeItems = elements.filter(el => el.tableScope === scope);
      renderTagGroup(scopeItems);
    }

    return lines.join('\n');
  }

  download(content: string, filename: string, mime: string): void {
    const blob = new Blob([content], { type: mime });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  async copyToClipboard(content: string): Promise<void> {
    if (navigator.clipboard?.writeText) {
      await navigator.clipboard.writeText(content);
      return;
    }
    // Fallback cho browser cũ / context không có clipboard API.
    const ta = document.createElement('textarea');
    ta.value = content;
    ta.style.position = 'fixed';
    ta.style.opacity = '0';
    document.body.appendChild(ta);
    ta.select();
    document.execCommand('copy');
    document.body.removeChild(ta);
  }

  /** Build a compact state summary string from defined state keys, e.g. "disabled=false; empty=true". */
  private buildStateSummary(state: SdAutoidElementState): string {
    const parts: string[] = [];
    if (state.disabled !== undefined) parts.push(`disabled=${state.disabled}`);
    if (state.loading !== undefined) parts.push(`loading=${state.loading}`);
    if (state.empty !== undefined) parts.push(`empty=${state.empty}`);
    if (state.invalid !== undefined) parts.push(`invalid=${state.invalid}`);
    if (state.opened !== undefined) parts.push(`opened=${state.opened}`);
    if (state.count !== undefined) parts.push(`count=${state.count}`);
    if (state.dataValue !== undefined) parts.push(`data-value=${state.dataValue}`);
    return parts.join('; ');
  }

  private q(v: string | number): string {
    const s = String(v ?? '').replace(/"/g, '""');
    return `"${s}"`;
  }

  private mdCell(s: string): string {
    return (s || '').replace(/\|/g, '\\|').replace(/\n/g, ' ');
  }

  private toCamel(autoid: string): string {
    const parts = autoid.split(/[-_]/).filter(Boolean);
    return parts.map((p, i) => (i === 0 ? p : p[0].toUpperCase() + p.slice(1))).join('');
  }

  private toPascal(title: string): string {
    return title
      .split(/[^a-zA-Z0-9]+/)
      .filter(Boolean)
      .map(p => p[0].toUpperCase() + p.slice(1))
      .join('');
  }
}
