import type {
  DocCategory,
  DocComponentLoader,
  DocNavigationGroup,
  DocPageDefinition,
  DocPageStatus,
  DocsRegistry,
  DocTab,
} from './documentation.models';
import { DOC_CATEGORIES, DOC_CATEGORY_LABELS } from './documentation.models';
import { SHOWCASE_EXAMPLE_MANIFEST } from '../generated/example-manifest.generated';

const INTERACTION_GATED_PREVIEWS = new Set(['components/editor', 'components/form-generic', 'components/upload-file']);

export const DOC_TABS: readonly DocTab[] = [
  { id: 'overview', label: 'Overview' },
  { id: 'styling', label: 'Styling' },
  { id: 'api', label: 'API' },
  { id: 'examples', label: 'Examples' },
];

interface DocPageSeed {
  readonly id?: string;
  readonly category: DocCategory;
  readonly slug: string;
  readonly title: string;
  readonly description: string;
  readonly selector: string | null;
  readonly importPath: string;
  readonly publishedDocId: string | null;
  readonly keywords: readonly string[];
  readonly status: DocPageStatus;
  readonly demoSectionCount: number;
  readonly loadComponent: DocComponentLoader;
  readonly demoPath?: string;
  readonly legacyPaths?: readonly string[];
}

function defineDocPage(seed: DocPageSeed): DocPageDefinition {
  const id = seed.id ?? `${seed.category}-${seed.slug}`;
  const canonicalPath = `${seed.category}/${seed.slug}`;
  const demoPath = seed.demoPath ?? canonicalPath;
  const legacyPaths = [...new Set([canonicalPath, demoPath, ...(seed.legacyPaths ?? [])])];
  const exampleManifest = SHOWCASE_EXAMPLE_MANIFEST.filter(example => example.pageKey === demoPath);
  if (exampleManifest.length !== seed.demoSectionCount) {
    throw new Error(
      `Example manifest for ${demoPath} has ${exampleManifest.length} entries; expected ${seed.demoSectionCount}. Run npm run generate:showcase-examples.`
    );
  }

  return {
    id,
    category: seed.category,
    slug: seed.slug,
    title: seed.title,
    description: seed.description,
    selector: seed.selector,
    importPath: seed.importPath,
    publishedDocId: seed.publishedDocId,
    keywords: [seed.title, seed.slug, seed.category, seed.importPath, ...(seed.selector ? [seed.selector] : []), ...seed.keywords],
    tabs: DOC_TABS,
    status: seed.status,
    sourcePath: `versions/v19/projects/showcase/src/app/pages/${demoPath}/${demoPath.split('/').at(-1)}-demo.component.ts`,
    legacyPath: demoPath,
    legacyPaths,
    demoSectionCount: seed.demoSectionCount,
    examples: exampleManifest.map(example => ({
      id: `${id}-${example.sectionId ?? 'showcase'}`,
      sourceKey: example.sourceKey,
      sectionId: example.sectionId,
      title: example.title,
      description: example.description,
      activation: INTERACTION_GATED_PREVIEWS.has(demoPath) ? 'interaction' : 'viewport',
      loadComponent: seed.loadComponent,
    })),
  };
}

interface PublishedDocPageSeed {
  readonly category: DocCategory;
  readonly slug: string;
  readonly title: string;
  readonly description: string;
  readonly selector?: string | null;
  readonly importPath: string;
  readonly publishedDocId: string;
  readonly keywords?: readonly string[];
}

/** Creates a catalog entry for published reference content that has no local live demo. */
function definePublishedDocPage(seed: PublishedDocPageSeed): DocPageDefinition {
  const canonicalPath = `${seed.category}/${seed.slug}`;
  return {
    id: `${seed.category}-${seed.slug}`,
    category: seed.category,
    slug: seed.slug,
    title: seed.title,
    description: seed.description,
    selector: seed.selector ?? null,
    importPath: seed.importPath,
    publishedDocId: seed.publishedDocId,
    keywords: [seed.title, seed.slug, seed.category, seed.importPath, ...(seed.selector ? [seed.selector] : []), ...(seed.keywords ?? [])],
    tabs: DOC_TABS,
    status: 'stable',
    sourcePath: null,
    legacyPath: canonicalPath,
    legacyPaths: [canonicalPath],
    demoSectionCount: 0,
    examples: [],
  };
}

const COMPONENT_PAGES = [
  defineDocPage({
    category: 'components',
    slug: 'anchor',
    title: 'Anchor',
    description: 'Điều hướng scroll-spy dạng cột và tự đánh dấu mục tương ứng khi cuộn.',
    selector: 'sd-anchor, sd-anchor-item',
    importPath: '@sdcorejs/angular/components/anchor',
    publishedDocId: 'components/anchor/sd-anchor',
    keywords: ['scroll spy', 'table of contents', 'toc', 'navigation'],
    status: 'stable',
    demoSectionCount: 2,
    loadComponent: () => import('../../pages/components/anchor/anchor-demo.component').then(m => m.AnchorDemoComponent),
  }),
  defineDocPage({
    category: 'components',
    slug: 'avatar',
    title: 'Avatar',
    description: 'Ảnh đại diện tròn với fallback chữ cái đầu và màu ổn định theo tên.',
    selector: 'sd-avatar',
    importPath: '@sdcorejs/angular/components/avatar',
    publishedDocId: 'components/avatar/sd-avatar',
    keywords: ['profile', 'initials', 'image', 'user'],
    status: 'stable',
    demoSectionCount: 4,
    loadComponent: () => import('../../pages/components/avatar/avatar-demo.component').then(m => m.AvatarDemoComponent),
  }),
  defineDocPage({
    category: 'components',
    slug: 'badge',
    title: 'Badge',
    description: 'Nhãn trạng thái và số đếm với các dạng icon, round và tag.',
    selector: 'sd-badge',
    importPath: '@sdcorejs/angular/components/badge',
    publishedDocId: 'components/badge/sd-badge',
    keywords: ['status', 'count', 'tag', 'label'],
    status: 'stable',
    demoSectionCount: 10,
    loadComponent: () => import('../../pages/components/badge/badge-demo.component').then(m => m.BadgeDemoComponent),
  }),
  defineDocPage({
    category: 'components',
    slug: 'button',
    title: 'Button',
    description: 'Nút thao tác với nhiều biến thể, kích thước, icon và trạng thái loading.',
    selector: 'sd-button',
    importPath: '@sdcorejs/angular/components/button',
    publishedDocId: 'components/button/sd-button',
    keywords: ['action', 'submit', 'loading', 'icon'],
    status: 'stable',
    demoSectionCount: 7,
    loadComponent: () => import('../../pages/components/button/button-demo.component').then(m => m.ButtonDemoComponent),
  }),
  defineDocPage({
    category: 'components',
    slug: 'chart',
    title: 'Chart',
    description: 'Biểu đồ Chart.js cho dashboard và báo cáo: line, bar, pie và doughnut.',
    selector: 'sd-line-chart, sd-bar-chart, sd-pie-chart, sd-doughnut-chart',
    importPath: '@sdcorejs/angular/components/chart',
    publishedDocId: 'components/chart/sd-chart',
    keywords: ['chart.js', 'dashboard', 'report', 'visualization'],
    status: 'stable',
    demoSectionCount: 3,
    loadComponent: () => import('../../pages/components/chart/chart-demo.component').then(m => m.ChartDemoComponent),
  }),
  defineDocPage({
    category: 'components',
    slug: 'code-editor',
    title: 'Code Editor',
    description: 'Trình soạn thảo mã nguồn có Prism highlighting và thao tác sao chép.',
    selector: 'sd-code-editor',
    importPath: '@sdcorejs/angular/components/code-editor',
    publishedDocId: 'components/code-editor/sd-code-editor',
    keywords: ['prism', 'source code', 'syntax highlighting', 'copy'],
    status: 'stable',
    demoSectionCount: 3,
    loadComponent: () => import('../../pages/components/code-editor/code-editor-demo.component').then(m => m.CodeEditorDemoComponent),
  }),
  defineDocPage({
    category: 'components',
    slug: 'document-builder',
    title: 'Document Builder',
    description: 'Trình dựng tài liệu nâng cao cho mẫu hợp đồng và văn bản nội bộ.',
    selector: 'sd-document-builder',
    importPath: '@sdcorejs/angular/components/document-builder',
    publishedDocId: 'components/document-builder/sd-document-builder',
    keywords: ['document', 'contract', 'template', 'editor'],
    status: 'stable',
    demoSectionCount: 1,
    loadComponent: () =>
      import('../../pages/components/document-builder/document-builder-demo.component').then(m => m.DocumentBuilderDemoComponent),
  }),
  defineDocPage({
    category: 'components',
    slug: 'editor',
    title: 'Editor',
    description: 'Rich text editor dựa trên CKEditor 5 với validation và FormGroup binding.',
    selector: 'sd-editor',
    importPath: '@sdcorejs/angular/components/editor',
    publishedDocId: 'components/editor/sd-editor',
    keywords: ['ckeditor', 'rich text', 'html', 'form'],
    status: 'stable',
    demoSectionCount: 2,
    loadComponent: () => import('../../pages/components/editor/editor-demo.component').then(m => m.EditorDemoComponent),
  }),
  defineDocPage({
    id: 'modules-integrations-generic',
    category: 'components',
    slug: 'generic',
    title: 'Form Generic',
    description: 'Dynamic form builder và renderer với drag/drop, conditions và runtime preview.',
    selector: 'sd-form-builder, sd-form-render',
    importPath: '@sdcorejs/angular/components/form-generic',
    publishedDocId: 'modules/generic/sd-generic',
    keywords: ['dynamic form', 'schema', 'builder', 'renderer'],
    status: 'stable',
    demoSectionCount: 1,
    demoPath: 'components/form-generic',
    legacyPaths: ['modules-integrations/generic'],
    loadComponent: () => import('../../pages/components/form-generic/form-generic-demo.component').then(m => m.FormGenericDemoComponent),
  }),
  defineDocPage({
    category: 'components',
    slug: 'history',
    title: 'History',
    description: 'Timeline dọc cho lịch sử thay đổi và phê duyệt của một bản ghi.',
    selector: 'sd-history',
    importPath: '@sdcorejs/angular/components/history',
    publishedDocId: 'components/history/sd-history',
    keywords: ['timeline', 'audit', 'approval', 'activity'],
    status: 'stable',
    demoSectionCount: 3,
    loadComponent: () => import('../../pages/components/history/history-demo.component').then(m => m.HistoryDemoComponent),
  }),
  defineDocPage({
    category: 'modules-integrations',
    slug: 'icon',
    title: 'Icon',
    description: 'Facade icon dùng chung cho Material filled, Material outlined và Lucide SVG.',
    selector: 'sd-icon',
    importPath: '@sdcorejs/angular/modules/icon',
    publishedDocId: 'modules/icon/sd-icon',
    keywords: ['material icons', 'lucide', 'svg', 'font set'],
    status: 'stable',
    demoSectionCount: 5,
    demoPath: 'components/icon',
    loadComponent: () => import('../../pages/components/icon/icon-demo.component').then(m => m.IconDemoComponent),
  }),
  defineDocPage({
    category: 'modules-integrations',
    slug: 'icon-configuration',
    title: 'Icon Configuration',
    description: 'Cấu hình default font set và alias icon dùng xuyên suốt Core UI.',
    selector: 'sd-icon',
    importPath: '@sdcorejs/angular/modules/icon',
    publishedDocId: 'modules/icon/sd-icon',
    keywords: ['icon provider', 'configuration', 'defaultFontSet', 'alias'],
    status: 'stable',
    demoSectionCount: 2,
    demoPath: 'components/icon-configuration',
    loadComponent: () =>
      import('../../pages/components/icon-configuration/icon-configuration-demo.component').then(m => m.IconConfigurationDemoComponent),
  }),
  defineDocPage({
    category: 'components',
    slug: 'import-excel',
    title: 'Import Excel',
    description: 'Quy trình import Excel gồm template, upload, validation, preview và dữ liệu hợp lệ.',
    selector: 'sd-import-excel',
    importPath: '@sdcorejs/angular/components/import-excel',
    publishedDocId: 'components/import-excel/sd-import-excel',
    keywords: ['xlsx', 'upload', 'validation', 'template'],
    status: 'stable',
    demoSectionCount: 1,
    loadComponent: () => import('../../pages/components/import-excel/import-excel-demo.component').then(m => m.ImportExcelDemoComponent),
  }),
  defineDocPage({
    category: 'components',
    slug: 'inform',
    title: 'Inform',
    description: 'Banner thông báo neo trên trang cho lỗi, cảnh báo và thông tin.',
    selector: 'sd-inform',
    importPath: '@sdcorejs/angular/components/inform',
    publishedDocId: 'components/inform/sd-inform',
    keywords: ['alert', 'banner', 'warning', 'message'],
    status: 'stable',
    demoSectionCount: 5,
    loadComponent: () => import('../../pages/components/inform/inform-demo.component').then(m => m.InformDemoComponent),
  }),
  defineDocPage({
    category: 'components',
    slug: 'mini-editor',
    title: 'Mini Editor',
    description: 'Editor gọn cho comment và ghi chú ngắn, hỗ trợ HTML hoặc Markdown.',
    selector: 'sd-mini-editor',
    importPath: '@sdcorejs/angular/components/mini-editor',
    publishedDocId: 'components/mini-editor/sd-mini-editor',
    keywords: ['comment', 'markdown', 'mention', 'rich text'],
    status: 'stable',
    demoSectionCount: 2,
    loadComponent: () => import('../../pages/components/mini-editor/mini-editor-demo.component').then(m => m.MiniEditorDemoComponent),
  }),
  defineDocPage({
    category: 'components',
    slug: 'modal',
    title: 'Modal',
    description: 'Dialog và bottom sheet với các slot header/footer dùng chung.',
    selector: 'sd-modal',
    importPath: '@sdcorejs/angular/components/modal',
    publishedDocId: 'components/modal/sd-modal',
    keywords: ['dialog', 'bottom sheet', 'overlay', 'popup'],
    status: 'stable',
    demoSectionCount: 7,
    loadComponent: () => import('../../pages/components/modal/modal-demo.component').then(m => m.ModalDemoComponent),
  }),
  defineDocPage({
    category: 'components',
    slug: 'operator',
    title: 'Operator',
    description: 'Bộ chọn toán tử so sánh dùng cho các bộ lọc nâng cao.',
    selector: 'sd-operator',
    importPath: '@sdcorejs/angular/components/operator',
    publishedDocId: 'components/operator/sd-operator',
    keywords: ['filter', 'comparison', 'query', 'condition'],
    status: 'stable',
    demoSectionCount: 4,
    loadComponent: () => import('../../pages/components/operator/operator-demo.component').then(m => m.OperatorDemoComponent),
  }),
  defineDocPage({
    category: 'components',
    slug: 'org-chart',
    title: 'Org Chart',
    description: 'Sơ đồ tổ chức dạng cây với card node và trạng thái thu gọn/mở rộng.',
    selector: 'sd-org-chart',
    importPath: '@sdcorejs/angular/components/org-chart',
    publishedDocId: 'components/org-chart/sd-org-chart',
    keywords: ['organization', 'hierarchy', 'tree', 'node'],
    status: 'stable',
    demoSectionCount: 4,
    loadComponent: () => import('../../pages/components/org-chart/org-chart-demo.component').then(m => m.OrgChartDemoComponent),
  }),
  defineDocPage({
    category: 'components',
    slug: 'preview',
    title: 'Preview',
    description: 'Bộ xem ảnh và PDF hỗ trợ zoom, rotate, fullscreen và download.',
    selector: 'sd-preview-image, sd-preview-pdf',
    importPath: '@sdcorejs/angular/components/preview',
    publishedDocId: 'components/preview/sd-preview',
    keywords: ['image', 'pdf', 'lightbox', 'viewer'],
    status: 'stable',
    demoSectionCount: 3,
    loadComponent: () => import('../../pages/components/preview/preview-demo.component').then(m => m.PreviewDemoComponent),
  }),
  defineDocPage({
    category: 'components',
    slug: 'query-bar',
    title: 'Query Bar',
    description: 'Thanh chip lọc hỗ trợ AND/OR, saved filters, popover và inline mode.',
    selector: 'sd-query-bar',
    importPath: '@sdcorejs/angular/components/query-bar',
    publishedDocId: 'components/query-bar/sd-query-bar',
    keywords: ['filter', 'chips', 'saved filter', 'search'],
    status: 'stable',
    demoSectionCount: 2,
    loadComponent: () => import('../../pages/components/query-bar/query-bar-demo.component').then(m => m.QueryBarDemoComponent),
  }),
  defineDocPage({
    category: 'components',
    slug: 'query-builder',
    title: 'Query Builder',
    description: 'Bộ dựng điều kiện dạng cây với nhóm AND/OR lồng nhau và nhiều kiểu trường.',
    selector: 'sd-query-builder',
    importPath: '@sdcorejs/angular/components/query-builder',
    publishedDocId: 'components/query-builder/sd-query-builder',
    keywords: ['filter tree', 'condition', 'and or', 'field comparison'],
    status: 'stable',
    demoSectionCount: 7,
    loadComponent: () => import('../../pages/components/query-builder/query-builder-demo.component').then(m => m.QueryBuilderDemoComponent),
  }),
  defineDocPage({
    category: 'components',
    slug: 'quick-action',
    title: 'Quick Action',
    description: 'Toolbar nổi ở đáy màn hình cho các thao tác hàng loạt.',
    selector: 'sd-quick-action',
    importPath: '@sdcorejs/angular/components/quick-action',
    publishedDocId: 'components/quick-action/sd-quick-action',
    keywords: ['bulk action', 'floating toolbar', 'selection', 'command'],
    status: 'stable',
    demoSectionCount: 3,
    loadComponent: () => import('../../pages/components/quick-action/quick-action-demo.component').then(m => m.QuickActionDemoComponent),
  }),
  defineDocPage({
    category: 'components',
    slug: 'section',
    title: 'Section',
    description: 'Card nhóm thông tin với header, body, footer và các item nhãn/giá trị.',
    selector: 'sd-section, sd-section-item',
    importPath: '@sdcorejs/angular/components/section',
    publishedDocId: 'components/section/sd-section',
    keywords: ['card', 'details', 'header', 'footer'],
    status: 'stable',
    demoSectionCount: 7,
    loadComponent: () => import('../../pages/components/section/section-demo.component').then(m => m.SectionDemoComponent),
  }),
  defineDocPage({
    category: 'components',
    slug: 'side-drawer',
    title: 'Side Drawer',
    description: 'Panel bên phải cho form, detail và filter với các slot header/footer.',
    selector: 'sd-side-drawer',
    importPath: '@sdcorejs/angular/components/side-drawer',
    publishedDocId: 'components/side-drawer/sd-side-drawer',
    keywords: ['drawer', 'panel', 'detail', 'form'],
    status: 'stable',
    demoSectionCount: 6,
    loadComponent: () => import('../../pages/components/side-drawer/side-drawer-demo.component').then(m => m.SideDrawerDemoComponent),
  }),
  defineDocPage({
    category: 'components',
    slug: 'splitter',
    title: 'Splitter',
    description: 'Chia không gian thành các panel có thể kéo resize theo chiều ngang hoặc dọc.',
    selector: 'sd-splitter, sd-splitter-panel',
    importPath: '@sdcorejs/angular/components/splitter',
    publishedDocId: 'components/splitter/sd-splitter',
    keywords: ['resize', 'panel', 'layout', 'collapsible'],
    status: 'stable',
    demoSectionCount: 3,
    loadComponent: () => import('../../pages/components/splitter/splitter-demo.component').then(m => m.SplitterDemoComponent),
  }),
  defineDocPage({
    category: 'components',
    slug: 'stepper',
    title: 'Stepper',
    description: 'Luồng nhiều bước hỗ trợ horizontal/vertical, linear forms và error states.',
    selector: 'sd-stepper, sd-step',
    importPath: '@sdcorejs/angular/components/stepper',
    publishedDocId: 'components/stepper/sd-stepper',
    keywords: ['wizard', 'steps', 'linear', 'workflow'],
    status: 'stable',
    demoSectionCount: 9,
    loadComponent: () => import('../../pages/components/stepper/stepper-demo.component').then(m => m.StepperDemoComponent),
  }),
  defineDocPage({
    category: 'components',
    slug: 'tab',
    title: 'Tab Group',
    description: 'Tab khai báo hỗ trợ icon, badge, disabled, closable và lazy content.',
    selector: 'sd-tab-group, sd-tab',
    importPath: '@sdcorejs/angular/components/tab',
    publishedDocId: 'components/tab/sd-tab',
    keywords: ['tabs', 'navigation', 'closable', 'lazy'],
    status: 'stable',
    demoSectionCount: 9,
    loadComponent: () => import('../../pages/components/tab/tab-demo.component').then(m => m.TabDemoComponent),
  }),
  defineDocPage({
    category: 'components',
    slug: 'tab-router',
    title: 'Tab Router',
    description: 'Router shell dạng browser tab, giữ state khi chuyển qua lại giữa URL.',
    selector: 'sd-tab-router-outlet, sd-tab-router-nav, sd-tab-router-item',
    importPath: '@sdcorejs/angular/components/tab-router',
    publishedDocId: 'components/tab-router/sd-tab-router',
    keywords: ['router', 'workspace', 'browser tabs', 'state'],
    status: 'stable',
    demoSectionCount: 3,
    loadComponent: () => import('../../pages/components/tab-router/tab-router-demo.component').then(m => m.TabRouterDemoComponent),
  }),
  defineDocPage({
    category: 'components',
    slug: 'table',
    title: 'Table',
    description: 'Bảng dữ liệu local/server với pagination, filter, selection, commands và export.',
    selector: 'sd-table',
    importPath: '@sdcorejs/angular/components/table',
    publishedDocId: 'components/table/sd-table',
    keywords: ['data grid', 'pagination', 'filter', 'selection', 'server side'],
    status: 'stable',
    demoSectionCount: 19,
    loadComponent: () => import('../../pages/components/table/table-demo.component').then(m => m.TableDemoComponent),
  }),
  defineDocPage({
    category: 'components',
    slug: 'tree',
    title: 'Tree',
    description: 'Cây static/lazy cho danh mục và tổ chức, hỗ trợ selection, commands và templates.',
    selector: 'sd-tree',
    importPath: '@sdcorejs/angular/components/tree',
    publishedDocId: 'components/tree/sd-tree',
    keywords: ['hierarchy', 'lazy tree', 'selection', 'filter'],
    status: 'stable',
    demoSectionCount: 5,
    loadComponent: () => import('../../pages/components/tree/tree-demo.component').then(m => m.TreeDemoComponent),
  }),
  defineDocPage({
    category: 'components',
    slug: 'upload-file',
    title: 'Upload File',
    description: 'Upload file và image bằng kéo thả, validation, multi-file và preview.',
    selector: 'sd-upload-file',
    importPath: '@sdcorejs/angular/components/upload-file',
    publishedDocId: 'components/upload-file/sd-upload-file',
    keywords: ['file', 'drag drop', 'validation', 'preview'],
    status: 'stable',
    demoSectionCount: 3,
    loadComponent: () => import('../../pages/components/upload-file/upload-file-demo.component').then(m => m.UploadFileDemoComponent),
  }),
  defineDocPage({
    category: 'components',
    slug: 'view',
    title: 'View',
    description: 'Hiển thị cặp nhãn/giá trị chỉ đọc trên trang chi tiết.',
    selector: 'sd-view',
    importPath: '@sdcorejs/angular/components/view',
    publishedDocId: 'components/view/sd-view',
    keywords: ['read only', 'detail', 'label value', 'display'],
    status: 'stable',
    demoSectionCount: 3,
    loadComponent: () => import('../../pages/components/view/view-demo.component').then(m => m.ViewDemoComponent),
  }),
] as const;

const FORM_PAGES = [
  defineDocPage({
    category: 'forms',
    slug: 'autocomplete',
    title: 'Autocomplete',
    description: 'Nhập để lọc và chọn một giá trị, hỗ trợ cache, addable và validation.',
    selector: 'sd-autocomplete',
    importPath: '@sdcorejs/angular/forms/autocomplete',
    publishedDocId: 'forms/autocomplete/sd-autocomplete',
    keywords: ['typeahead', 'search', 'addable', 'dropdown'],
    status: 'stable',
    demoSectionCount: 6,
    loadComponent: () => import('../../pages/forms/autocomplete/autocomplete-demo.component').then(m => m.AutocompleteDemoComponent),
  }),
  defineDocPage({
    category: 'forms',
    slug: 'checkbox',
    title: 'Checkbox',
    description: 'Ô đánh dấu boolean với theme colors và các trạng thái disabled/viewed.',
    selector: 'sd-checkbox',
    importPath: '@sdcorejs/angular/forms/checkbox',
    publishedDocId: 'forms/checkbox/sd-checkbox',
    keywords: ['boolean', 'checked', 'toggle', 'form'],
    status: 'stable',
    demoSectionCount: 6,
    loadComponent: () => import('../../pages/forms/checkbox/checkbox-demo.component').then(m => m.CheckboxDemoComponent),
  }),
  defineDocPage({
    category: 'forms',
    slug: 'chip',
    title: 'Chip',
    description: 'Nhập danh sách tag dạng chuỗi với thao tác thêm và xoá chip.',
    selector: 'sd-chip',
    importPath: '@sdcorejs/angular/forms/chip',
    publishedDocId: 'forms/chip/sd-chip',
    keywords: ['tags', 'token', 'multiple values', 'list'],
    status: 'stable',
    demoSectionCount: 5,
    loadComponent: () => import('../../pages/forms/chip/chip-demo.component').then(m => m.ChipDemoComponent),
  }),
  defineDocPage({
    category: 'forms',
    slug: 'chip-calendar',
    title: 'Chip Calendar',
    description: 'Chọn nhiều ngày và hiển thị mỗi ngày dưới dạng chip.',
    selector: 'sd-chip-calendar',
    importPath: '@sdcorejs/angular/forms/chip-calendar',
    publishedDocId: 'forms/chip-calendar/sd-chip-calendar',
    keywords: ['multiple dates', 'calendar', 'chips', 'schedule'],
    status: 'stable',
    demoSectionCount: 4,
    loadComponent: () => import('../../pages/forms/chip-calendar/chip-calendar-demo.component').then(m => m.ChipCalendarDemoComponent),
  }),
  defineDocPage({
    category: 'forms',
    slug: 'date',
    title: 'Date',
    description: 'Chọn một ngày và bind hai chiều với chuỗi ngày ISO.',
    selector: 'sd-date',
    importPath: '@sdcorejs/angular/forms/date',
    publishedDocId: 'forms/date/sd-date',
    keywords: ['datepicker', 'calendar', 'iso date', 'form'],
    status: 'stable',
    demoSectionCount: 5,
    loadComponent: () => import('../../pages/forms/date/date-demo.component').then(m => m.DateDemoComponent),
  }),
  defineDocPage({
    category: 'forms',
    slug: 'date-range',
    title: 'Date Range',
    description: 'Chọn khoảng thời gian từ ngày bắt đầu đến ngày kết thúc.',
    selector: 'sd-date-range',
    importPath: '@sdcorejs/angular/forms/date-range',
    publishedDocId: 'forms/date-range/sd-date-range',
    keywords: ['range picker', 'from to', 'calendar', 'period'],
    status: 'stable',
    demoSectionCount: 4,
    loadComponent: () => import('../../pages/forms/date-range/date-range-demo.component').then(m => m.DateRangeDemoComponent),
  }),
  defineDocPage({
    category: 'forms',
    slug: 'datetime',
    title: 'Datetime',
    description: 'Chọn ngày và giờ trong cùng một control.',
    selector: 'sd-datetime',
    importPath: '@sdcorejs/angular/forms/datetime',
    publishedDocId: 'forms/datetime/sd-datetime',
    keywords: ['date time picker', 'calendar', 'time', 'schedule'],
    status: 'stable',
    demoSectionCount: 4,
    loadComponent: () => import('../../pages/forms/datetime/datetime-demo.component').then(m => m.DatetimeDemoComponent),
  }),
  defineDocPage({
    category: 'forms',
    slug: 'inline-text',
    title: 'Inline Text',
    description: 'Primitive input borderless, content-hug dùng cho inline editing.',
    selector: 'sd-inline-text',
    importPath: '@sdcorejs/angular/forms/inline-text',
    publishedDocId: 'forms/inline-text/sd-inline-text',
    keywords: ['inline edit', 'borderless', 'content hug', 'primitive'],
    status: 'stable',
    demoSectionCount: 5,
    loadComponent: () => import('../../pages/forms/inline-text/inline-text-demo.component').then(m => m.InlineTextDemoComponent),
  }),
  defineDocPage({
    category: 'forms',
    slug: 'input',
    title: 'Input',
    description: 'Input một dòng với helper text, validators và các trạng thái khoá/xem.',
    selector: 'sd-input',
    importPath: '@sdcorejs/angular/forms/input',
    publishedDocId: 'forms/input/sd-input',
    keywords: ['text field', 'validation', 'password', 'email'],
    status: 'stable',
    demoSectionCount: 7,
    loadComponent: () => import('../../pages/forms/input/input-demo.component').then(m => m.InputDemoComponent),
  }),
  defineDocPage({
    category: 'forms',
    slug: 'input-color',
    title: 'Input Color',
    description: 'Nhập mã HEX với swatch và bảng chọn màu.',
    selector: 'sd-input-color',
    importPath: '@sdcorejs/angular/forms/input-color',
    publishedDocId: 'forms/input-color/sd-input-color',
    keywords: ['color picker', 'hex', 'swatch', 'rgba'],
    status: 'stable',
    demoSectionCount: 5,
    loadComponent: () => import('../../pages/forms/input-color/input-color-demo.component').then(m => m.InputColorDemoComponent),
  }),
  defineDocPage({
    category: 'forms',
    slug: 'input-number',
    title: 'Input Number',
    description: 'Nhập số có định dạng hàng nghìn, min/max, prefix và suffix.',
    selector: 'sd-input-number',
    importPath: '@sdcorejs/angular/forms/input-number',
    publishedDocId: 'forms/input-number/sd-input-number',
    keywords: ['number field', 'currency', 'min max', 'format'],
    status: 'stable',
    demoSectionCount: 6,
    loadComponent: () => import('../../pages/forms/input-number/input-number-demo.component').then(m => m.InputNumberDemoComponent),
  }),
  defineDocPage({
    category: 'forms',
    slug: 'radio',
    title: 'Radio',
    description: 'Chọn một giá trị trong nhóm theo layout hàng ngang hoặc dọc.',
    selector: 'sd-radio',
    importPath: '@sdcorejs/angular/forms/radio',
    publishedDocId: 'forms/radio/sd-radio',
    keywords: ['single choice', 'options', 'row', 'column'],
    status: 'stable',
    demoSectionCount: 4,
    loadComponent: () => import('../../pages/forms/radio/radio-demo.component').then(m => m.RadioDemoComponent),
  }),
  defineDocPage({
    category: 'forms',
    slug: 'select',
    title: 'Select',
    description: 'Dropdown chọn một giá trị với templates và footer actions.',
    selector: 'sd-select',
    importPath: '@sdcorejs/angular/forms/select',
    publishedDocId: 'forms/select/sd-select',
    keywords: ['dropdown', 'options', 'footer action', 'template'],
    status: 'stable',
    demoSectionCount: 10,
    loadComponent: () => import('../../pages/forms/select/select-demo.component').then(m => m.SelectDemoComponent),
  }),
  defineDocPage({
    category: 'forms',
    slug: 'switch',
    title: 'Switch',
    description: 'Công tắc boolean với theme colors và các trạng thái disabled/viewed.',
    selector: 'sd-switch',
    importPath: '@sdcorejs/angular/forms/switch',
    publishedDocId: 'forms/switch/sd-switch',
    keywords: ['toggle', 'boolean', 'on off', 'settings'],
    status: 'stable',
    demoSectionCount: 5,
    loadComponent: () => import('../../pages/forms/switch/switch-demo.component').then(m => m.SwitchDemoComponent),
  }),
  defineDocPage({
    category: 'forms',
    slug: 'textarea',
    title: 'Textarea',
    description: 'Input nhiều dòng với helper text, length validation và các trạng thái khoá.',
    selector: 'sd-textarea',
    importPath: '@sdcorejs/angular/forms/textarea',
    publishedDocId: 'forms/textarea/sd-textarea',
    keywords: ['multiline', 'long text', 'validation', 'form'],
    status: 'stable',
    demoSectionCount: 4,
    loadComponent: () => import('../../pages/forms/textarea/textarea-demo.component').then(m => m.TextareaDemoComponent),
  }),
] as const;

const SERVICE_PAGES = [
  defineDocPage({
    category: 'services',
    slug: 'confirm',
    title: 'Confirm',
    description: 'Promise-based confirmation dialogs cho xác nhận, input, choice và date/datetime.',
    selector: null,
    importPath: '@sdcorejs/angular/services/confirm',
    publishedDocId: 'services/confirm/sd-confirm',
    keywords: ['dialog', 'confirmation', 'prompt', 'promise'],
    status: 'stable',
    demoSectionCount: 9,
    loadComponent: () => import('../../pages/services/confirm/confirm-demo.component').then(m => m.ConfirmDemoComponent),
  }),
  defineDocPage({
    category: 'services',
    slug: 'docx',
    title: 'Docx',
    description: 'Chuyển đổi tệp DOCX sang HTML bằng pandoc.wasm.',
    selector: null,
    importPath: '@sdcorejs/angular/services/docx',
    publishedDocId: 'services/docx/sd-docx',
    keywords: ['word', 'pandoc', 'convert', 'html'],
    status: 'stable',
    demoSectionCount: 3,
    loadComponent: () => import('../../pages/services/docx/docx-demo.component').then(m => m.DocxDemoComponent),
  }),
  defineDocPage({
    category: 'services',
    slug: 'excel',
    title: 'Excel',
    description: 'Export/import XLSX và CSV, tạo template và parse worksheet.',
    selector: null,
    importPath: '@sdcorejs/angular/services/excel',
    publishedDocId: 'services/excel/sd-excel',
    keywords: ['xlsx', 'csv', 'export', 'import', 'template'],
    status: 'stable',
    demoSectionCount: 3,
    loadComponent: () => import('../../pages/services/excel/excel-demo.component').then(m => m.ExcelDemoComponent),
  }),
  defineDocPage({
    category: 'services',
    slug: 'loading',
    title: 'Loading',
    description: 'Phủ loading spinner lên body hoặc một phần tử đích theo CSS selector.',
    selector: null,
    importPath: '@sdcorejs/angular/services/loading',
    publishedDocId: 'services/loading/sd-loading',
    keywords: ['spinner', 'overlay', 'busy', 'async'],
    status: 'stable',
    demoSectionCount: 4,
    loadComponent: () => import('../../pages/services/loading/loading-demo.component').then(m => m.LoadingDemoComponent),
  }),
  defineDocPage({
    category: 'services',
    slug: 'notify',
    title: 'Notify',
    description: 'Toast notifications cho success, info, warning và error.',
    selector: null,
    importPath: '@sdcorejs/angular/services/notify',
    publishedDocId: 'services/notify/sd-notify',
    keywords: ['toast', 'notification', 'feedback', 'message'],
    status: 'stable',
    demoSectionCount: 4,
    loadComponent: () => import('../../pages/services/notify/notify-demo.component').then(m => m.NotifyDemoComponent),
  }),
  defineDocPage({
    category: 'services',
    slug: 'storage',
    title: 'Storage',
    description: 'Typed local/session storage handles với cache và Observable updates.',
    selector: null,
    importPath: '@sdcorejs/angular/services/storage',
    publishedDocId: 'services/storage/sd-storage',
    keywords: ['localStorage', 'sessionStorage', 'cache', 'observable'],
    status: 'stable',
    demoSectionCount: 3,
    loadComponent: () => import('../../pages/services/storage/storage-demo.component').then(m => m.StorageDemoComponent),
  }),
] as const;

const PUBLISHED_ONLY_PAGES = [
  definePublishedDocPage({
    category: 'guides',
    slug: 'introduction',
    title: 'Introduction',
    description: 'Install the package, configure global styles and providers, and learn the recommended Core UI conventions.',
    importPath: '@sdcorejs/angular',
    publishedDocId: 'README',
    keywords: ['getting started', 'installation', 'setup', 'theming'],
  }),
  definePublishedDocPage({
    category: 'guides',
    slug: 'style-guide',
    title: 'Assets & SCSS Reference',
    description: 'Public design tokens, utility classes, grid helpers and theming entry points shipped with the package.',
    importPath: '@sdcorejs/angular/assets/scss/sd-core',
    publishedDocId: 'assets/STYLE-GUIDE',
    keywords: ['styles', 'scss', 'tokens', 'utilities', 'theme'],
  }),
  definePublishedDocPage({
    category: 'guides',
    slug: 'e2e-attributes',
    title: 'E2E Test Attributes',
    description: 'Stable runtime data attributes and selector patterns for reliable end-to-end tests.',
    importPath: '@sdcorejs/angular',
    publishedDocId: 'docs/E2E-ATTRIBUTES',
    keywords: ['testing', 'selectors', 'playwright', 'cypress', 'automation'],
  }),
  definePublishedDocPage({
    category: 'components',
    slug: 'autoid-inspector',
    title: 'Auto ID Inspector',
    description: 'Inspects generated element identifiers to support stable automation and debugging workflows.',
    selector: 'sd-autoid-inspector',
    importPath: '@sdcorejs/angular/components/autoid-inspector',
    publishedDocId: 'components/autoid-inspector/sd-autoid-inspector',
    keywords: ['auto id', 'e2e', 'inspector', 'testing'],
  }),
  definePublishedDocPage({
    category: 'forms',
    slug: 'label',
    title: 'Label',
    description: 'Consistent form labels with required, optional and supporting presentation states.',
    selector: 'sd-label',
    importPath: '@sdcorejs/angular/forms/label',
    publishedDocId: 'forms/label/sd-label',
    keywords: ['form label', 'required', 'caption'],
  }),
  definePublishedDocPage({
    category: 'directives',
    slug: 'desktop',
    title: 'Desktop Directive',
    description: 'Conditionally renders content for desktop layouts using the shared responsive breakpoint contract.',
    selector: '*sdDesktop',
    importPath: '@sdcorejs/angular/directives',
    publishedDocId: 'directives/src/sd-desktop',
    keywords: ['responsive', 'desktop', 'breakpoint'],
  }),
  definePublishedDocPage({
    category: 'directives',
    slug: 'hover-copy',
    title: 'Hover Copy Directive',
    description: 'Adds an accessible copy affordance to values that users frequently move to the clipboard.',
    selector: '[sdHoverCopy]',
    importPath: '@sdcorejs/angular/directives',
    publishedDocId: 'directives/src/sd-hover-copy',
    keywords: ['clipboard', 'copy', 'hover'],
  }),
  definePublishedDocPage({
    category: 'directives',
    slug: 'href',
    title: 'Href Directive',
    description: 'Applies consistent link behavior to SDCoreJS navigation targets.',
    selector: '[sdHref]',
    importPath: '@sdcorejs/angular/directives',
    publishedDocId: 'directives/src/sd-href',
    keywords: ['link', 'navigation', 'anchor'],
  }),
  definePublishedDocPage({
    category: 'directives',
    slug: 'mobile',
    title: 'Mobile Directive',
    description: 'Conditionally renders content for mobile layouts using the shared responsive breakpoint contract.',
    selector: '*sdMobile',
    importPath: '@sdcorejs/angular/directives',
    publishedDocId: 'directives/src/sd-mobile',
    keywords: ['responsive', 'mobile', 'breakpoint'],
  }),
  definePublishedDocPage({
    category: 'directives',
    slug: 'scroll',
    title: 'Scroll Directive',
    description: 'Observes scroll position and exposes reusable scrolling behavior to host components.',
    selector: '[sdScroll]',
    importPath: '@sdcorejs/angular/directives',
    publishedDocId: 'directives/src/sd-scroll',
    keywords: ['scroll', 'position', 'event'],
  }),
  definePublishedDocPage({
    category: 'directives',
    slug: 'tooltip',
    title: 'Tooltip Directive',
    description: 'Provides concise contextual help for controls and truncated values.',
    selector: '[sdTooltip]',
    importPath: '@sdcorejs/angular/directives',
    publishedDocId: 'directives/src/sd-tooltip',
    keywords: ['tooltip', 'hint', 'help'],
  }),
  definePublishedDocPage({
    category: 'services',
    slug: 'api',
    title: 'API Service',
    description: 'Shared HTTP request conventions for SDCoreJS Angular applications.',
    importPath: '@sdcorejs/angular/services/api',
    publishedDocId: 'services/api/sd-api',
    keywords: ['http', 'request', 'backend', 'rest'],
  }),
  definePublishedDocPage({
    category: 'services',
    slug: 'cache',
    title: 'Cache Service',
    description: 'Caches asynchronous application data with a reusable typed service contract.',
    importPath: '@sdcorejs/angular/services/cache',
    publishedDocId: 'services/cache/sd-cache',
    keywords: ['cache', 'data', 'performance'],
  }),
  definePublishedDocPage({
    category: 'services',
    slug: 'license',
    title: 'License Service',
    description: 'Loads and validates application license information for protected features.',
    importPath: '@sdcorejs/angular/services/license',
    publishedDocId: 'services/license/sd-license',
    keywords: ['license', 'validation', 'feature access'],
  }),
  definePublishedDocPage({
    category: 'modules-integrations',
    slug: 'core-configuration',
    title: 'Core Configuration',
    description: 'Global injection token and options used to configure SDCoreJS Angular behavior.',
    importPath: '@sdcorejs/angular/configurations',
    publishedDocId: 'configurations/src/sd-core.configuration',
    keywords: ['configuration', 'provider', 'token'],
  }),
  definePublishedDocPage({
    category: 'modules-integrations',
    slug: 'global-error-handler',
    title: 'Global Error Handler',
    description: 'Centralizes unhandled Angular errors and user-facing failure reporting.',
    importPath: '@sdcorejs/angular/handlers',
    publishedDocId: 'handlers/global-error.handler',
    keywords: ['error handler', 'exceptions', 'logging'],
  }),
  definePublishedDocPage({
    category: 'modules-integrations',
    slug: 'i18n',
    title: 'Internationalization',
    description: 'Locale configuration and translation primitives for multilingual applications.',
    importPath: '@sdcorejs/angular/i18n',
    publishedDocId: 'i18n/i18n',
    keywords: ['i18n', 'locale', 'translation', 'language'],
  }),
  definePublishedDocPage({
    category: 'modules-integrations',
    slug: 'no-internet-interceptor',
    title: 'No Internet Interceptor',
    description: 'Handles offline HTTP failures consistently across application requests.',
    importPath: '@sdcorejs/angular/interceptors',
    publishedDocId: 'interceptors/no-internet/no-internet.interceptor',
    keywords: ['http interceptor', 'offline', 'network'],
  }),
  definePublishedDocPage({
    category: 'modules-integrations',
    slug: 'unauthorized-interceptor',
    title: 'Unauthorized Interceptor',
    description: 'Coordinates application behavior when an HTTP request is unauthorized.',
    importPath: '@sdcorejs/angular/interceptors',
    publishedDocId: 'interceptors/unauthorized/unauthorized.interceptor',
    keywords: ['http interceptor', '401', 'authorization'],
  }),
  definePublishedDocPage({
    category: 'modules-integrations',
    slug: 'auth',
    title: 'Auth Module',
    description: 'Authentication primitives and providers for SDCoreJS Angular applications.',
    importPath: '@sdcorejs/angular/modules/auth',
    publishedDocId: 'modules/auth/sd-auth',
    keywords: ['authentication', 'login', 'session'],
  }),
  definePublishedDocPage({
    category: 'modules-integrations',
    slug: 'keycloak',
    title: 'Keycloak Module',
    description: 'Keycloak authentication, session renewal and authorization integration.',
    importPath: '@sdcorejs/angular/modules/keycloak',
    publishedDocId: 'modules/keycloak/sd-keycloak',
    keywords: ['keycloak', 'oidc', 'authentication', 'authorization'],
  }),
  defineDocPage({
    category: 'modules-integrations',
    slug: 'layout',
    title: 'Layout Module',
    description: 'Application shell and responsive layout building blocks for Core UI portals.',
    selector: 'sd-layout, sd-page',
    importPath: '@sdcorejs/angular/modules/layout',
    publishedDocId: 'modules/layout/sd-layout',
    keywords: ['layout', 'shell', 'responsive', 'portal'],
    status: 'stable',
    demoSectionCount: 1,
    demoPath: 'modules/layout',
    loadComponent: () => import('../../pages/modules/layout/layout-demo.component').then(m => m.LayoutDemoComponent),
  }),
  definePublishedDocPage({
    category: 'modules-integrations',
    slug: 'permission',
    title: 'Permission Module',
    description: 'Permission providers and UI gates for role-aware application features.',
    importPath: '@sdcorejs/angular/modules/permission',
    publishedDocId: 'modules/permission/sd-permission',
    keywords: ['permission', 'role', 'authorization', 'access'],
  }),
  definePublishedDocPage({
    category: 'pipes-utilities',
    slug: 'empty',
    title: 'Empty Pipe',
    description: 'Displays a consistent fallback for empty values.',
    importPath: '@sdcorejs/angular/pipes',
    publishedDocId: 'pipes/src/empty',
    keywords: ['sdEmpty', 'fallback', 'empty value'],
  }),
  definePublishedDocPage({
    category: 'pipes-utilities',
    slug: 'format-date',
    title: 'Format Date Pipe',
    description: 'Formats date-only values with the configured application locale.',
    importPath: '@sdcorejs/angular/pipes',
    publishedDocId: 'pipes/src/format-date',
    keywords: ['sdFormatDate', 'date', 'format'],
  }),
  definePublishedDocPage({
    category: 'pipes-utilities',
    slug: 'format-datetime',
    title: 'Format Datetime Pipe',
    description: 'Formats date-time values with the configured application locale.',
    importPath: '@sdcorejs/angular/pipes',
    publishedDocId: 'pipes/src/format-datetime',
    keywords: ['sdFormatDatetime', 'datetime', 'format'],
  }),
  definePublishedDocPage({
    category: 'pipes-utilities',
    slug: 'format-number',
    title: 'Format Number Pipe',
    description: 'Formats numeric values with locale-aware separators and precision.',
    importPath: '@sdcorejs/angular/pipes',
    publishedDocId: 'pipes/src/format-number',
    keywords: ['sdFormatNumber', 'number', 'format'],
  }),
  definePublishedDocPage({
    category: 'pipes-utilities',
    slug: 'safe-html',
    title: 'Safe HTML Pipe',
    description: 'Marks trusted HTML for controlled rendering in Angular templates.',
    importPath: '@sdcorejs/angular/pipes',
    publishedDocId: 'pipes/src/safe-html',
    keywords: ['sdSafeHtml', 'html', 'sanitization'],
  }),
  definePublishedDocPage({
    category: 'pipes-utilities',
    slug: 'time-different',
    title: 'Time Difference Pipe',
    description: 'Presents elapsed time between date-time values in a reusable display format.',
    importPath: '@sdcorejs/angular/pipes',
    publishedDocId: 'pipes/src/time-different',
    keywords: ['sdTimeDifferent', 'duration', 'elapsed time'],
  }),
  definePublishedDocPage({
    category: 'pipes-utilities',
    slug: 'view',
    title: 'View Pipe',
    description: 'Normalizes values for compact read-only presentation.',
    importPath: '@sdcorejs/angular/pipes',
    publishedDocId: 'pipes/src/view',
    keywords: ['sdView', 'display', 'read only'],
  }),
  definePublishedDocPage({
    category: 'pipes-utilities',
    slug: 'extensions',
    title: 'Utility Extensions',
    description: 'Shared extension utilities used across SDCoreJS Angular applications.',
    importPath: '@sdcorejs/angular/utilities/extensions',
    publishedDocId: 'utilities/extensions/extensions',
    keywords: ['utilities', 'extensions', 'helpers'],
  }),
  definePublishedDocPage({
    category: 'pipes-utilities',
    slug: 'models',
    title: 'Utility Models',
    description: 'Common public models and type contracts shared by Core UI features.',
    importPath: '@sdcorejs/angular/utilities/models',
    publishedDocId: 'utilities/models/models',
    keywords: ['utilities', 'models', 'types', 'interfaces'],
  }),
] as const;

function mergePublishedPages(pages: readonly DocPageDefinition[]): DocPageDefinition[] {
  const byPublishedId = new Map<string, DocPageDefinition>();
  for (const page of pages) {
    const publishedId = page.publishedDocId ?? page.id;
    const existing = byPublishedId.get(publishedId);
    if (!existing) {
      byPublishedId.set(publishedId, page);
      continue;
    }

    const mergedExamples = page.examples.map(example => ({
      ...example,
      id: `${existing.id}-example-${page.slug}-${(example.sectionId ?? 'showcase').replace(/^example-/, '')}`,
    }));
    byPublishedId.set(publishedId, {
      ...existing,
      keywords: [...new Set([...existing.keywords, ...page.keywords])],
      legacyPaths: [...new Set([...(existing.legacyPaths ?? [existing.legacyPath]), ...(page.legacyPaths ?? [page.legacyPath])])],
      demoSectionCount: existing.demoSectionCount + page.demoSectionCount,
      examples: [...existing.examples, ...mergedExamples],
    });
  }
  return [...byPublishedId.values()];
}

const CATEGORY_INDEX = new Map(DOC_CATEGORIES.map((category, index) => [category, index]));

export const DOC_PAGES: readonly DocPageDefinition[] = mergePublishedPages([
  ...COMPONENT_PAGES,
  ...FORM_PAGES,
  ...SERVICE_PAGES,
  ...PUBLISHED_ONLY_PAGES,
]).sort(
  (left, right) =>
    (CATEGORY_INDEX.get(left.category) ?? 0) - (CATEGORY_INDEX.get(right.category) ?? 0) || left.title.localeCompare(right.title)
);

const CATEGORY_METADATA: readonly Omit<DocNavigationGroup, 'pages'>[] = [
  {
    category: 'guides',
    title: DOC_CATEGORY_LABELS.guides,
    description: 'Installation, styling and testing guidance for a reliable first implementation.',
    icon: 'menu_book',
  },
  {
    category: 'components',
    title: DOC_CATEGORY_LABELS.components,
    description: 'Composable UI building blocks for application screens and workflows.',
    icon: 'widgets',
  },
  {
    category: 'forms',
    title: DOC_CATEGORY_LABELS.forms,
    description: 'Inputs, pickers and controls with consistent validation behavior.',
    icon: 'edit_note',
  },
  {
    category: 'directives',
    title: DOC_CATEGORY_LABELS.directives,
    description: 'Template behavior for responsive layouts, navigation and interaction details.',
    icon: 'code',
  },
  {
    category: 'services',
    title: DOC_CATEGORY_LABELS.services,
    description: 'Application services for feedback, files, data access and client state.',
    icon: 'build',
  },
  {
    category: 'modules-integrations',
    title: DOC_CATEGORY_LABELS['modules-integrations'],
    description: 'Configuration, authentication, permissions and platform integrations.',
    icon: 'extension',
  },
  {
    category: 'pipes-utilities',
    title: DOC_CATEGORY_LABELS['pipes-utilities'],
    description: 'Formatting pipes and shared public utility contracts.',
    icon: 'functions',
  },
];

/** Navigation groups derived from the canonical page registry. */
export const DOC_NAV_GROUPS: readonly DocNavigationGroup[] = CATEGORY_METADATA.map(group => ({
  ...group,
  pages: DOC_PAGES.filter(page => page.category === group.category),
}));

export const DOCS_REGISTRY: DocsRegistry = {
  pages: DOC_PAGES,
  groups: DOC_NAV_GROUPS,
};

const DOC_PAGES_BY_PATH = new Map<string, DocPageDefinition>();
for (const page of DOC_PAGES) {
  DOC_PAGES_BY_PATH.set(`${page.category}/${page.slug}`, page);
  for (const legacyPath of page.legacyPaths ?? [page.legacyPath]) DOC_PAGES_BY_PATH.set(legacyPath, page);
}

export function getDocPagesByCategory(category: DocCategory): readonly DocPageDefinition[] {
  return DOC_PAGES.filter(page => page.category === category);
}

export function findDocNavigationGroup(category: string | null | undefined): DocNavigationGroup | undefined {
  return DOC_NAV_GROUPS.find(group => group.category === category);
}

export function findDocPage(category: DocCategory, slug: string): DocPageDefinition | undefined {
  return DOC_PAGES_BY_PATH.get(`${category}/${slug}`);
}

export function findDocPageById(id: string): DocPageDefinition | undefined {
  return DOC_PAGES.find(page => page.id === id);
}
