import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';

import {
  generateShowcaseChangelog,
  parseChangelog,
  renderGeneratedModule,
} from './generate-showcase-changelog.mjs';

const CHANGELOG_FIXTURE = `# Changelog

## [Unreleased]

### Added

- Work in progress

## [1.3] - 2026-08-01

Future release summary.

### Added

#### Search

- Global search
  - Keyboard navigation
  - Focus restoration

### Security

- Sanitized Markdown output

## [1.2] - 2026-07-11

Boundary release summary.

### Fixed

- Hidden paginator height

## [1.1] - 2026-07-10

### Fixed

- Older release that must be filtered out
`;

test('retains Unreleased and filters releases before suffix 1.2', () => {
  const changelog = parseChangelog(CHANGELOG_FIXTURE, { startSuffix: '1.2' });

  assert.deepEqual(
    changelog.releases.map(release => release.suffix),
    [null, '1.3', '1.2'],
  );
  assert.equal(changelog.releases[0].unreleased, true);
  assert.equal(changelog.releases[0].sections[0].items[0].text, 'Work in progress');
});

test('derives Angular 19/20/21 package versions and stable release anchors', () => {
  const changelog = parseChangelog(CHANGELOG_FIXTURE, { startSuffix: '1.2' });
  const release = changelog.releases.find(item => item.suffix === '1.2');

  assert.ok(release);
  assert.equal(release.anchor, 'release-1-2');
  assert.deepEqual(release.packageVersions, [
    { angularMajor: 19, version: '19.1.2' },
    { angularMajor: 20, version: '20.1.2' },
    { angularMajor: 21, version: '21.1.2' },
  ]);
});

test('parses nested subsections and nested Markdown list items', () => {
  const changelog = parseChangelog(CHANGELOG_FIXTURE, { startSuffix: '1.2' });
  const release = changelog.releases.find(item => item.suffix === '1.3');
  const added = release?.sections.find(section => section.key === 'added');
  const search = added?.children[0];

  assert.ok(search);
  assert.equal(search.title, 'Search');
  assert.equal(search.anchor, 'release-1-3-added-search');
  assert.equal(search.items[0].text, 'Global search');
  assert.deepEqual(
    search.items[0].children.map(item => item.text),
    ['Keyboard navigation', 'Focus restoration'],
  );
  assert.match(added.markdown, /#### Search/);
});

test('keeps future releases and tolerates missing optional sections', () => {
  const changelog = parseChangelog(CHANGELOG_FIXTURE, { startSuffix: '1.2' });
  const future = changelog.releases.find(item => item.suffix === '1.3');
  const boundary = changelog.releases.find(item => item.suffix === '1.2');

  assert.ok(future);
  assert.equal(future.date, '2026-08-01');
  assert.deepEqual(future.sections.map(section => section.key), ['added', 'security']);
  assert.ok(boundary);
  assert.deepEqual(boundary.sections.map(section => section.key), ['fixed']);
  assert.equal(boundary.sections.some(section => section.key === 'added'), false);
});

test('renders a typed generated module with a generated-file warning', () => {
  const changelog = parseChangelog(CHANGELOG_FIXTURE, { startSuffix: '1.2' });
  const output = renderGeneratedModule(changelog);

  assert.match(output, /AUTO-GENERATED/);
  assert.match(output, /Do not edit this file directly/);
  assert.match(output, /satisfies readonly ShowcaseChangelogRelease\[\]/);
  assert.match(output, /SHOWCASE_CHANGELOG_START_SUFFIX = '1\.2'/);
});

test('generates a TypeScript artifact from a changelog file', () => {
  const tempRoot = mkdtempSync(join(tmpdir(), 'sdcorejs-changelog-'));
  const inputPath = join(tempRoot, 'CHANGELOG.md');
  const outputPath = join(tempRoot, 'changelog.generated.ts');

  try {
    writeFileSync(inputPath, CHANGELOG_FIXTURE, 'utf8');
    const result = generateShowcaseChangelog({ inputPath, outputPath, startSuffix: '1.2' });
    const output = readFileSync(outputPath, 'utf8');

    assert.equal(result.releases.length, 3);
    assert.match(output, /19\.1\.2/);
    assert.match(output, /release-1-3-added-search/);
  } finally {
    rmSync(tempRoot, { recursive: true, force: true });
  }
});
