import { ChangeDetectionStrategy, Component, inject, signal, viewChild } from '@angular/core';
import { DemoPageComponent, DemoSectionComponent } from '../../../shared/demo-page.component';
import {
  SdFileExplorer,
  SdFileExplorerItem,
  SdFileExplorerOpenEvent,
  SdFileExplorerOption,
} from '@sdcorejs/angular/components/file-explorer';
import { SdConfirmService } from '@sdcorejs/angular/services/confirm';

const DAY = 86_400_000;

/** Waits `ms`, rejecting with an `AbortError` as soon as `signal` aborts. */
function wait(ms: number, signal?: AbortSignal): Promise<void> {
  return new Promise((resolve, reject) => {
    const abort = () => reject(new DOMException('Aborted', 'AbortError'));
    if (signal?.aborted) return abort();
    const timer = setTimeout(resolve, ms);
    const onAbort = () => {
      clearTimeout(timer);
      abort();
    };
    signal?.addEventListener('abort', onAbort, { once: true });
  });
}

/** Reports progress in 50 steps over `durationMs`, like an XHR `progress` event would. */
async function simulateTransfer(
  total: number,
  durationMs: number,
  progress: (loaded: number, total?: number) => void,
  signal: AbortSignal
): Promise<void> {
  const steps = 50;
  for (let step = 1; step <= steps; step++) {
    await wait(durationMs / steps, signal);
    progress(Math.round((total * step) / steps), total);
  }
}

function normalize(value: string): string {
  return value
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/đ/g, 'd')
    .toLowerCase();
}

const COVER_SVG = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 300 200">
  <rect width="300" height="200" fill="#d9e5f6"/>
  <circle cx="210" cy="62" r="24" fill="#f7e8c4"/>
  <path d="M0 184 L88 72 L150 150 L208 98 L300 184 Z" fill="#7ea6c8"/>
  <path d="M0 184 L112 108 L190 184 Z" fill="#4e7fa9"/>
</svg>`;

function svgBlob(svg: string): Blob {
  return new Blob([svg], { type: 'image/svg+xml' });
}

function svgDataUrl(svg: string): string {
  return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`;
}

/** One-page PDF generated in the browser so the demo needs no asset. */
function pdfBlob(title: string): Blob {
  const text = title.replace(/[()\\]/g, '');
  const stream = `BT /F1 26 Tf 72 740 Td (${text}) Tj ET BT /F1 13 Tf 72 700 Td (Generated by the sd-file-explorer demo.) Tj ET`;
  const pdf = [
    '%PDF-1.4',
    '1 0 obj <</Type /Catalog /Pages 2 0 R>> endobj',
    '2 0 obj <</Type /Pages /Kids [3 0 R] /Count 1>> endobj',
    '3 0 obj <</Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents 4 0 R /Resources <</Font <</F1 5 0 R>>>>>> endobj',
    `4 0 obj <</Length ${stream.length}>> stream`,
    stream,
    'endstream endobj',
    '5 0 obj <</Type /Font /Subtype /Type1 /BaseFont /Helvetica>> endobj',
    'trailer <</Root 1 0 R>>',
    '%%EOF',
  ].join('\n');
  return new Blob([pdf], { type: 'application/pdf' });
}

interface DemoEntry extends SdFileExplorerItem {
  /** File content served by preview / download. */
  content?: () => Blob;
}

const XLSX = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
const DOCX = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';

function seed(): DemoEntry[] {
  const now = Date.now();
  const csv = () => new Blob(['Hạng mục,Tuần 1,Tuần 2\nThiết kế,40%,80%\n'], { type: 'text/csv' });
  const doc = (name: string) => () => new Blob([`${name}\n`], { type: 'text/plain' });
  return [
    { id: 'du-an', parentId: null, name: 'Dự án', kind: 'folder' },
    { id: 'website', parentId: 'du-an', name: 'Website', kind: 'folder', hasChildren: false },
    { id: 'thiet-ke', parentId: 'du-an', name: 'Thiết kế', kind: 'folder', hasChildren: false },
    { id: 'tai-lieu', parentId: null, name: 'Tài liệu', kind: 'folder', hasChildren: false },
    { id: 'hinh-anh', parentId: null, name: 'Hình ảnh', kind: 'folder', hasChildren: false },
    {
      id: 'huong-dan',
      parentId: null,
      name: 'Hướng dẫn sử dụng.pdf',
      kind: 'file',
      mimeType: 'application/pdf',
      size: 2_516_582,
      modifiedAt: now - 2 * 3_600_000,
      content: () => pdfBlob('Huong dan su dung'),
    },
    {
      id: 'ke-hoach',
      parentId: null,
      name: 'Bảng kế hoạch.xlsx',
      kind: 'file',
      mimeType: XLSX,
      size: 866_304,
      modifiedAt: now - DAY,
      content: csv,
    },
    {
      id: 'anh-bia',
      parentId: null,
      name: 'Ảnh bìa sản phẩm.jpg',
      kind: 'file',
      mimeType: 'image/jpeg',
      size: 1_887_437,
      modifiedAt: now - 3 * DAY,
      content: () => svgBlob(COVER_SVG),
    },
    {
      id: 'brief',
      parentId: 'du-an',
      name: 'Brief dự án.docx',
      kind: 'file',
      mimeType: DOCX,
      size: 48_128,
      modifiedAt: now - 5 * DAY,
      content: doc('Brief'),
    },
    {
      id: 'sitemap',
      parentId: 'website',
      name: 'Sơ đồ trang.pdf',
      kind: 'file',
      mimeType: 'application/pdf',
      size: 320_512,
      modifiedAt: now - 8 * DAY,
      content: () => pdfBlob('So do trang'),
    },
    {
      id: 'logo',
      parentId: 'thiet-ke',
      name: 'Logo.png',
      kind: 'file',
      mimeType: 'image/png',
      size: 94_208,
      modifiedAt: now - 12 * DAY,
      thumbnailUrl: svgDataUrl(COVER_SVG),
      content: () => svgBlob(COVER_SVG),
    },
    {
      id: 'quy-trinh',
      parentId: 'tai-lieu',
      name: 'Quy trình phê duyệt.pdf',
      kind: 'file',
      mimeType: 'application/pdf',
      size: 1_153_433,
      modifiedAt: now - 2 * DAY,
      content: () => pdfBlob('Quy trinh phe duyet'),
    },
    {
      id: 'hop-dong',
      parentId: 'tai-lieu',
      name: 'Hợp đồng mẫu.docx',
      kind: 'file',
      mimeType: DOCX,
      size: 212_992,
      modifiedAt: now - 40 * DAY,
      content: doc('Hop dong'),
    },
    {
      id: 'bao-cao',
      parentId: 'tai-lieu',
      name: 'Báo cáo quý 3.xlsx',
      kind: 'file',
      mimeType: XLSX,
      size: 530_432,
      modifiedAt: now - 6 * DAY,
      content: csv,
    },
    {
      id: 'banner',
      parentId: 'hinh-anh',
      name: 'Banner trang chủ.png',
      kind: 'file',
      mimeType: 'image/png',
      size: 2_202_009,
      modifiedAt: now - 4 * DAY,
      thumbnailUrl: svgDataUrl(COVER_SVG),
      content: () => svgBlob(COVER_SVG),
    },
    {
      id: 'video',
      parentId: 'hinh-anh',
      name: 'Giới thiệu sản phẩm.mp4',
      kind: 'file',
      mimeType: 'video/mp4',
      size: 48_234_496,
      modifiedAt: now - 9 * DAY,
    },
  ];
}

/**
 * In-memory "drive" behind the demos. A real app replaces these methods with HTTP calls; the explorer only
 * sees the callbacks of `SdFileExplorerOption`.
 */
class DemoDrive {
  readonly #items = new Map<string, DemoEntry>();
  #seq = 0;

  constructor(entries: DemoEntry[] = seed()) {
    for (const entry of entries) this.#items.set(entry.id, entry);
  }

  async list(parentId: string | null, signal: AbortSignal, latency = 350): Promise<SdFileExplorerItem[]> {
    await wait(latency, signal);
    return [...this.#items.values()].filter(item => item.parentId === parentId).map(({ content: _content, ...item }) => item);
  }

  /** Recursive search below `parentId`, like most storage APIs. */
  async search(parentId: string | null, keyword: string, signal: AbortSignal): Promise<SdFileExplorerItem[]> {
    await wait(450, signal);
    const needle = normalize(keyword);
    return [...this.#items.values()]
      .filter(item => this.#isInside(item, parentId) && normalize(item.name).includes(needle))
      .map(({ content: _content, ...item }) => item);
  }

  preview(item: SdFileExplorerItem): Blob | null {
    return this.#items.get(item.id)?.content?.() ?? null;
  }

  async download(item: SdFileExplorerItem, progress: (loaded: number, total?: number) => void, signal: AbortSignal): Promise<Blob> {
    await wait(400, signal); // e.g. request a signed URL
    await simulateTransfer(item.size ?? 1, 1500, progress, signal);
    return this.#items.get(item.id)?.content?.() ?? new Blob([item.name], { type: 'text/plain' });
  }

  async upload(file: File, parentId: string | null, progress: (loaded: number, total?: number) => void, signal: AbortSignal) {
    await wait(600, signal);
    if (normalize(file.name).includes('loi')) throw new Error('Máy chủ từ chối tệp này (mô phỏng lỗi).');
    const duration = Math.min(14_000, Math.max(1500, file.size / 40));
    await simulateTransfer(file.size, duration, progress, signal);
    const entry: DemoEntry = {
      id: `upload-${++this.#seq}`,
      parentId,
      name: file.name,
      kind: 'file',
      mimeType: file.type || undefined,
      size: file.size,
      modifiedAt: Date.now(),
      content: () => file,
    };
    this.#items.set(entry.id, entry);
    return entry;
  }

  /** A real app would call its API to create a (possibly expiring) public link. */
  async share(item: SdFileExplorerItem, signal: AbortSignal): Promise<string> {
    await wait(700, signal);
    const token = Math.random().toString(36).slice(2, 10);
    return `https://drive.example.com/s/${encodeURIComponent(item.id)}-${token}`;
  }

  async createFolder(parentId: string | null, name: string): Promise<SdFileExplorerItem> {
    await wait(300);
    const exists = [...this.#items.values()].some(item => item.parentId === parentId && normalize(item.name) === normalize(name));
    if (exists) throw new Error(`Đã có mục tên "${name}" trong thư mục này.`);
    const folder: DemoEntry = { id: `folder-${++this.#seq}`, parentId, name, kind: 'folder', hasChildren: false, modifiedAt: Date.now() };
    this.#items.set(folder.id, folder);
    return folder;
  }

  /** Deletes items, folders with everything inside them. */
  async remove(ids: readonly string[]): Promise<void> {
    await wait(900);
    const doomed = new Set(ids);
    for (let grew = true; grew; ) {
      grew = false;
      for (const item of this.#items.values()) {
        if (item.parentId !== null && doomed.has(item.parentId) && !doomed.has(item.id)) {
          doomed.add(item.id);
          grew = true;
        }
      }
    }
    for (const id of doomed) this.#items.delete(id);
  }

  async rename(id: string, name: string): Promise<void> {
    await wait(400);
    const entry = this.#items.get(id);
    if (!entry) throw new Error('Mục này không còn tồn tại.');
    const taken = [...this.#items.values()].some(
      item => item.id !== id && item.parentId === entry.parentId && normalize(item.name) === normalize(name)
    );
    if (taken) throw new Error(`Đã có mục tên "${name}" trong thư mục này.`);
    this.#items.set(id, { ...entry, name, modifiedAt: Date.now() });
  }

  async move(ids: readonly string[], parentId: string | null): Promise<void> {
    await wait(700);
    for (const id of ids) {
      const entry = this.#items.get(id);
      if (entry) this.#items.set(id, { ...entry, parentId });
    }
  }

  #isInside(item: SdFileExplorerItem, folderId: string | null): boolean {
    if (folderId === null) return true;
    let parentId = item.parentId;
    while (parentId !== null) {
      if (parentId === folderId) return true;
      parentId = this.#items.get(parentId)?.parentId ?? null;
    }
    return false;
  }
}

/** Full option: every callback wired to the in-memory drive. */
function fullOption(drive: DemoDrive, autoId: string): SdFileExplorerOption {
  return {
    autoId,
    title: 'Tệp của tôi',
    description: 'File Explorer',
    list: ({ parentId, signal }) => drive.list(parentId, signal),
    search: ({ parentId, keyword, signal }) => drive.search(parentId, keyword, signal),
    preview: ({ item }) => drive.preview(item),
    download: ({ item, progress, signal }) => drive.download(item, progress, signal),
    upload: ({ file, parentId, progress, signal }) => drive.upload(file, parentId, progress, signal),
    share: ({ item, signal }) => drive.share(item, signal),
    createFolder: ({ parentId, name }) => drive.createFolder(parentId, name),
  };
}

@Component({
  selector: 'app-file-explorer-demo',
  standalone: true,
  imports: [DemoPageComponent, DemoSectionComponent, SdFileExplorer],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <demo-page
      #demoPage
      title="File Explorer"
      description="Trình duyệt tệp kiểu Google Drive trong một thẻ: cây thư mục, breadcrumb, list/grid, tìm kiếm, xem trước ảnh/PDF, tải lên kéo thả, tải xuống và hàng đợi truyền tệp. Không phụ thuộc backend — mọi thao tác đi qua callback của option.">
      @if (!demoPage.focusedSectionId || demoPage.focusedSectionId === 'example-day-du-tinh-nang') {
        <demo-section
          heading="Đầy đủ tính năng"
          [props]="[
            { name: 'option.list', value: 'lazy theo thư mục' },
            { name: 'option.search', value: 'debounce 300ms' },
            { name: 'option.preview', value: 'Blob ảnh / PDF' },
            { name: 'option.upload', value: 'chọn nhiều + kéo thả' },
            { name: 'option.download', value: 'Blob + progress' },
            { name: 'option.share', value: 'link chia sẻ' },
            { name: 'option.createFolder', value: 'callback' },
            { name: 'option.selector', value: 'chọn nhiều + actions' },
            { name: 'option.fileCommands', value: 'nút + nhóm menu' },
            { name: 'option.folderCommands', value: 'hàng, thẻ, cây' },
            { name: 'color', value: 'success / info / warning / error' },
            { name: 'reload()', value: 'method' },
            { name: '(open)', value: 'SdFileExplorerOpenEvent' },
          ]"
          note="Kéo thả tệp vào explorer hoặc bấm Tải tệp lên; tên tệp có chữ “loi” mô phỏng lỗi để thử nút Thử lại. Tích chọn nhiều tệp rồi dùng thanh chọn: nút phẳng mặc định light (Chuyển vào Tài liệu), nhóm mặc định text (Công cụ, menu ⋮), cùng cỡ 32px với lệnh của hàng. Màu ngữ nghĩa do trang demo tự khai báo: Đánh dấu đã duyệt (success), Xem thông tin (info), Lưu trữ (warning), Xóa tệp (error). Rê chuột (hoặc Tab) vào một hàng để thấy lệnh của tệp/thư mục; hợp đồng mẫu bị khóa chọn. Xác nhận, trạng thái loading và reload() đều do trang demo (consumer) tự làm.">
          <div class="frame frame--desktop">
            <sd-file-explorer #fullExplorer [option]="full" (open)="onOpen($event)" />
          </div>
          <p class="log" aria-live="polite">
            <strong>(open)</strong>
            @if (lastOpen(); as event) {
              {{ event }}
            } @else {
              — chưa mở tệp nào
            }
          </p>
          <p class="log" aria-live="polite">
            <strong>selector / commands</strong>
            @if (lastAction(); as action) {
              {{ action }}
            } @else {
              — chưa có thao tác nào
            }
          </p>
        </demo-section>
      }

      @if (!demoPage.focusedSectionId || demoPage.focusedSectionId === 'example-chi-xem-va-tai-xuong') {
        <demo-section
          heading="Chỉ xem và tải xuống"
          [props]="[
            { name: 'option.upload', value: 'không truyền' },
            { name: 'option.createFolder', value: 'không truyền' },
            { name: 'option.search', value: 'lọc tại chỗ' },
            { name: 'option.download', value: 'trả void (trình duyệt tự tải)' },
            { name: 'option.defaultView', value: 'grid' },
          ]"
          note="Callback nào không được cung cấp thì UI tương ứng biến mất. Không có search nên ô tìm kiếm lọc danh sách đã tải của thư mục hiện tại. Download trả void: explorer chỉ ghi nhận đã chuyển cho trình duyệt, không giả lập phần trăm.">
          <div class="frame frame--compact-height">
            <sd-file-explorer [option]="readOnly" />
          </div>
        </demo-section>
      }

      @if (!demoPage.focusedSectionId || demoPage.focusedSectionId === 'example-khung-hep-mobile') {
        <demo-section
          heading="Khung hẹp / mobile"
          [props]="[
            { name: 'width', value: '< 720px' },
            { name: 'cây thư mục', value: 'panel mở bằng nút menu' },
            { name: 'xem trước', value: 'phủ toàn khung' },
            { name: 'option.selector', value: 'thanh chọn 2 hàng' },
          ]"
          note="Layout đổi theo độ rộng của chính explorer (ResizeObserver), không theo viewport — đặt trong sidebar hẹp cũng tự chuyển. Thanh chọn giữ số lượng và nút bỏ chọn ở hàng đầu, các action xuống hàng sau; trên màn hình cảm ứng lệnh của hàng luôn hiện với vùng chạm 48px.">
          <div class="frame frame--mobile">
            <sd-file-explorer #mobileExplorer [option]="mobile" />
          </div>
        </demo-section>
      }

      @if (!demoPage.focusedSectionId || demoPage.focusedSectionId === 'example-loading-rong-va-loi') {
        <demo-section
          heading="Loading, rỗng và lỗi"
          [props]="[
            { name: 'list', value: 'Promise chậm / [] / reject' },
            { name: 'thử lại', value: 'gọi lại list' },
          ]"
          note="Thư mục “Lỗi lần đầu” reject ở lần gọi đầu tiên; bấm Thử lại (trong nội dung hoặc biểu tượng trên cây) sẽ thành công.">
          <div class="frame frame--compact-height">
            <sd-file-explorer [option]="states" />
          </div>
        </demo-section>
      }
    </demo-page>
  `,
  styles: `
    .frame {
      box-sizing: border-box;
      /* why: demo-section xếp con theo flex và co theo nội dung — frame phải tự giãn hết bề ngang,
         nếu không explorer đo được bề rộng nhỏ, vào layout compact rồi kẹt luôn ở đó. */
      width: 100%;
      height: 760px;
      padding: 16px;
      border-radius: 12px;
      background: #eef1f5;
    }
    .frame--compact-height {
      height: 560px;
    }
    .frame--mobile {
      width: 390px;
      max-width: 100%;
      height: 820px;
      padding: 8px;
    }
    .log {
      margin: 12px 0 0;
      font-size: 13px;
      color: var(--docs-text-secondary, #4a4a4a);
    }
  `,
})
export class FileExplorerDemoComponent {
  readonly #confirm = inject(SdConfirmService);
  // Angular queries cannot live on ES-private (#) fields.
  private readonly fullExplorer = viewChild<SdFileExplorer>('fullExplorer');
  private readonly mobileExplorer = viewChild<SdFileExplorer>('mobileExplorer');
  /** Ids whose action is running: their actions show a spinner and ignore new clicks until the drive answers. */
  readonly #busy = signal<ReadonlySet<string>>(new Set());
  readonly lastAction = signal<string | null>(null);

  readonly #fullDrive = new DemoDrive();
  readonly #mobileDrive = new DemoDrive();
  readonly full: SdFileExplorerOption = {
    ...fullOption(this.#fullDrive, 'full'),
    ...this.#manage(this.#fullDrive, () => this.fullExplorer()),
  };
  readonly mobile: SdFileExplorerOption = {
    ...fullOption(this.#mobileDrive, 'mobile'),
    ...this.#manage(this.#mobileDrive, () => this.mobileExplorer()),
  };

  readonly #readOnlyDrive = new DemoDrive();
  readonly readOnly: SdFileExplorerOption = {
    autoId: 'read-only',
    defaultView: 'grid',
    rootLabel: 'Thư viện',
    list: ({ parentId, signal }) => this.#readOnlyDrive.list(parentId, signal),
    preview: ({ item }) => this.#readOnlyDrive.preview(item),
    // Hand the file to the browser (for example a signed URL) and return nothing.
    download: ({ item }) => {
      const blob = this.#readOnlyDrive.preview(item) ?? new Blob([item.name]);
      const url = URL.createObjectURL(blob);
      const anchor = Object.assign(document.createElement('a'), { href: url, download: item.name });
      anchor.click();
      setTimeout(() => URL.revokeObjectURL(url), 30_000);
    },
  };

  #failedOnce = false;
  readonly states: SdFileExplorerOption = {
    autoId: 'states',
    title: 'Mô phỏng trạng thái',
    list: async ({ parentId, signal }) => {
      if (parentId === null) {
        await wait(800, signal);
        return [
          { id: 'empty', parentId: null, name: 'Thư mục trống', kind: 'folder', hasChildren: false },
          { id: 'slow', parentId: null, name: 'Tải chậm (3 giây)', kind: 'folder', hasChildren: false },
          { id: 'broken', parentId: null, name: 'Lỗi lần đầu', kind: 'folder', hasChildren: false },
        ];
      }
      if (parentId === 'slow') {
        await wait(3000, signal);
        return [{ id: 'late', parentId: 'slow', name: 'Đến muộn.pdf', kind: 'file', mimeType: 'application/pdf', size: 12_345 }];
      }
      if (parentId === 'broken' && !this.#failedOnce) {
        this.#failedOnce = true;
        await wait(500, signal);
        throw new Error('Máy chủ không phản hồi (mô phỏng).');
      }
      if (parentId === 'broken') {
        return [{ id: 'recovered', parentId: 'broken', name: 'Đã khôi phục.txt', kind: 'file', mimeType: 'text/plain', size: 512 }];
      }
      return [];
    },
  };

  readonly lastOpen = signal<string | null>(null);

  onOpen(event: SdFileExplorerOpenEvent): void {
    const path = event.path.map(folder => folder.name).join(' / ') || 'thư mục gốc';
    this.lastOpen.set(`${event.item.name} · ${path}`);
  }

  /**
   * Selection, bulk actions and per-item commands. The explorer only renders them and hands over the selected files
   * or the item; confirming, loading, errors and reload() are the page's job, as in a real app.
   *
   * Types are left unset, so the explorer defaults apply: a flat selector action is `light`, a group trigger and every
   * command `text`. The semantic colors (success / info / warning / error) are this page's data — the explorer never
   * colors an action by its meaning.
   */
  #manage(
    drive: DemoDrive,
    explorer: () => SdFileExplorer | undefined
  ): Pick<SdFileExplorerOption, 'selector' | 'fileCommands' | 'folderCommands'> {
    const busy = (items: readonly SdFileExplorerItem[]) => items.some(item => this.#busy().has(item.id));
    const remove = (items: readonly SdFileExplorerItem[]) => void this.#remove(drive, explorer, items);
    const rename = (item: SdFileExplorerItem) => void this.#rename(drive, explorer, item);
    const approve = (items: readonly SdFileExplorerItem[]) =>
      this.lastAction.set(`Đã đánh dấu duyệt ${this.#count(items)} (chỉ ghi nhật ký)`);
    const archive = (items: readonly SdFileExplorerItem[]) => this.lastAction.set(`Đã lưu trữ ${this.#count(items)} (chỉ ghi nhật ký)`);
    return {
      selector: {
        // The signed contract is locked: its checkbox is disabled and "select all" skips it.
        disabled: item => item.id === 'hop-dong',
        onSelect: (item, selected) => this.lastAction.set(`onSelect · ${item.name} · ${selected.length} tệp đang chọn`),
        onSelectAll: selected => this.lastAction.set(`onSelectAll · ${selected.length} tệp`),
        onClear: () => this.lastAction.set('onClear · đã bỏ chọn'),
        actions: [
          {
            title: 'Chuyển vào Tài liệu',
            prefixIcon: 'drive_file_move',
            loading: busy,
            click: items => void this.#moveToDocuments(drive, explorer, items),
          },
          { title: 'Đánh dấu đã duyệt', prefixIcon: 'task_alt', color: 'success', click: approve },
          {
            title: 'Công cụ',
            prefixIcon: 'construction',
            children: [
              { title: 'Xem thông tin', prefixIcon: 'info', color: 'info', click: items => this.#describe(items) },
              { title: 'Sao chép tên tệp', prefixIcon: 'content_copy', click: items => void this.#copyNames(items) },
              { title: 'Đổi tên', prefixIcon: 'edit', disabled: items => items.length !== 1, click: items => rename(items[0]) },
            ],
          },
          {
            tooltip: 'Thao tác khác với tệp đã chọn',
            children: [
              { title: 'Lưu trữ', prefixIcon: 'archive', color: 'warning', click: archive },
              { title: 'Xóa tệp', prefixIcon: 'delete', color: 'error', loading: busy, click: remove },
            ],
          },
        ],
      },
      fileCommands: [
        { tooltip: 'Tải bản sao', prefixIcon: 'file_download', click: item => this.#saveCopy(drive, item) },
        { tooltip: 'Xem thông tin', prefixIcon: 'info', color: 'info', click: item => this.#describe([item]) },
        {
          tooltip: 'Thao tác khác với tệp',
          children: [
            { title: 'Đổi tên', prefixIcon: 'edit', click: rename },
            { title: 'Đánh dấu đã duyệt', prefixIcon: 'task_alt', color: 'success', click: item => approve([item]) },
            { title: 'Lưu trữ', prefixIcon: 'archive', color: 'warning', click: item => archive([item]) },
            { title: 'Xóa tệp', prefixIcon: 'delete', color: 'error', loading: item => busy([item]), click: item => remove([item]) },
          ],
        },
      ],
      folderCommands: [
        { tooltip: 'Đổi tên thư mục', prefixIcon: 'edit', click: rename },
        {
          tooltip: 'Thao tác khác với thư mục',
          children: [
            { title: 'Lưu trữ thư mục', prefixIcon: 'archive', color: 'warning', click: item => archive([item]) },
            { title: 'Xóa thư mục', prefixIcon: 'delete', color: 'error', loading: item => busy([item]), click: item => remove([item]) },
          ],
        },
      ],
    };
  }

  #count(items: readonly SdFileExplorerItem[]): string {
    return items.length === 1 ? `“${items[0].name}”` : `${items.length} mục`;
  }

  #describe(items: readonly SdFileExplorerItem[]): void {
    const bytes = items.reduce((total, item) => total + (item.size ?? 0), 0);
    const size = new Intl.NumberFormat('vi-VN', { maximumFractionDigits: 1 }).format(bytes / 1_048_576);
    this.lastAction.set(`Thông tin · ${this.#count(items)} · ${size} MB`);
  }

  async #remove(drive: DemoDrive, explorer: () => SdFileExplorer | undefined, items: readonly SdFileExplorerItem[]): Promise<void> {
    const what = this.#count(items);
    try {
      await this.#confirm.confirm(`Xóa ${what}? Thao tác này không hoàn tác được.`, {
        title: 'Xóa',
        yesTitle: 'Xóa',
        yesButtonColor: 'error',
      });
    } catch {
      return; // the user cancelled
    }
    await this.#run(items, async () => {
      await drive.remove(items.map(item => item.id));
      this.lastAction.set(`Đã xóa ${what}`);
      explorer()?.reload();
    });
  }

  async #rename(drive: DemoDrive, explorer: () => SdFileExplorer | undefined, item: SdFileExplorerItem): Promise<void> {
    let name: string;
    try {
      name = await this.#confirm.withInput('Tên mới', {
        title: `Đổi tên “${item.name}”`,
        defaultValue: item.name,
        required: true,
        maxlength: 255,
      });
    } catch {
      return; // the user cancelled
    }
    const trimmed = name.trim();
    if (!trimmed || trimmed === item.name) return;
    await this.#run([item], async () => {
      await drive.rename(item.id, trimmed);
      this.lastAction.set(`Đã đổi tên thành “${trimmed}”`);
      explorer()?.reload();
    });
  }

  async #moveToDocuments(
    drive: DemoDrive,
    explorer: () => SdFileExplorer | undefined,
    items: readonly SdFileExplorerItem[]
  ): Promise<void> {
    await this.#run(items, async () => {
      await drive.move(
        items.map(item => item.id),
        'tai-lieu'
      );
      this.lastAction.set(`Đã chuyển ${items.length} tệp vào Tài liệu`);
      explorer()?.reload();
    });
  }

  async #copyNames(items: readonly SdFileExplorerItem[]): Promise<void> {
    try {
      await navigator.clipboard.writeText(items.map(item => item.name).join('\n'));
      this.lastAction.set(`Đã sao chép tên ${items.length} tệp`);
    } catch {
      this.lastAction.set('Trình duyệt chặn clipboard');
    }
  }

  #saveCopy(drive: DemoDrive, item: SdFileExplorerItem): void {
    const url = URL.createObjectURL(drive.preview(item) ?? new Blob([item.name]));
    Object.assign(document.createElement('a'), { href: url, download: item.name }).click();
    setTimeout(() => URL.revokeObjectURL(url), 30_000);
    this.lastAction.set(`Đã tải bản sao “${item.name}”`);
  }

  /** Marks the items busy while `work` runs, so their actions show a spinner and ignore repeated clicks. */
  async #run(items: readonly SdFileExplorerItem[], work: () => Promise<void>): Promise<void> {
    const ids = items.map(item => item.id);
    this.#busy.update(current => new Set([...current, ...ids]));
    try {
      await work();
    } catch (error) {
      this.lastAction.set(error instanceof Error ? `Lỗi: ${error.message}` : 'Lỗi không xác định');
    } finally {
      this.#busy.update(current => new Set([...current].filter(id => !ids.includes(id))));
    }
  }
}
